package main

LIGHT_ATTACK_STARTUP_FRAMES :: 6
LIGHT_ATTACK_ACTIVE_FRAMES :: 3
LIGHT_ATTACK_RECOVERY_FRAMES :: 10
LIGHT_ATTACK_TOTAL_FRAMES ::
	LIGHT_ATTACK_STARTUP_FRAMES + LIGHT_ATTACK_ACTIVE_FRAMES + LIGHT_ATTACK_RECOVERY_FRAMES
